site_name: Gestao de Risco UFSM
theme:
  name: material
  favicon: images/logos/favicon-32x32.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Alternar para tema escuro
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Alternar para tema claro
nav:
  - Home: index.md
  - Instalação: instalacao.md
  - Arquitetura: arquitetura.md
  - API: api.md
  - Banco de dados: banco-de-dados.md
  - Frontend: frontend.md
  - Design: design-prototipo.md
  - Testes: testes.md
  - Exemplos: exemplos-casos-de-uso.md
extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
